### ISSUE TITLE
Fails on New game

### ISSUE THREAD

**Issue by zampierilucas** [ricott1/rebels-in-the-sky#1]
I just tried the v1.03 version and got:
```
RUST_BACKTRACE=full ./rebels_x86_64-linux                                                                                                                                         lzampier@workstation
thread 'main' panicked at src/app.rs:103:55:
Failed to get world size: Os { code: 2, kind: NotFound, message: "No such file or directory" }
stack backtrace:
   0:     0x56105c01018c - <unknown>
   1:     0x56105c040adc - <unknown>
   2:     0x56105c00c79e - <unknown>
   3:     0x56105c00ff74 - <unknown>
   4:     0x56105c011bd3 - <unknown>
   5:     0x56105c0118ec - <unknown>
   6:     0x56105c0122ce - <unknown>
   7:     0x56105c012057 - <unknown>
   8:     0x56105c0106b6 - <unknown>
   9:     0x56105c011da2 - <unknown>
  10:     0x56105b955df3 - <unknown>
  11:     0x56105b9561fa - <unknown>
  12:     0x56105ba97bbb - <unknown>
  13:     0x56105b9f4b79 - <unknown>
  14:     0x56105ba999eb - <unknown>
  15:     0x56105b9bf418 - <unknown>
  16:     0x56105b9bab98 - <unknown>
  17:     0x56105b9b162b - <unknown>
  18:     0x56105b9bdcf4 - <unknown>
  19:     0x56105b9dd3b3 - <unknown>
  20:     0x56105b9cb399 - <unknown>
  21:     0x56105c0041eb - <unknown>
  22:     0x56105b9bf6c5 - <unknown>
  23:     0x7f2848dac14a - __libc_start_call_main
  24:     0x7f2848dac20b - __libc_start_main_impl
  25:     0x56105b9564be - <unknown>
  26:                0x0 - <unknown>
```

**Comment by ALTrilling** [comment]
I ran strace on the binary and found that it is trying to read from ~/.config/rebels/world.json
Create that file with the contents "{}" (without quotes) and then it should work.

**Comment by zampierilucas** [comment]
Thank you, @ALTrilling, I can confirm that:
```bash
echo "{}" > ~/.config/rebels/world.json
```
Fixes the issue.

**Comment by orhun** [comment]
Hey, having the same issue here.

I tried running that but now I get another error:

```
thread 'main' panicked at src/app.rs:112:13:
Failed to load world: missing field `dirty` at line 1 column 2
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by orhun** [comment]
FYI I created a new game and I no longer get the aforementioned error.

**Comment by ricott1** [comment]
Hello, thanks for the first issue! 

@zampierilucas Do you get that problem when starting a new game? Because it should create the world.json file automatically.

@orhun The problem is that I am introducing breaking changes with new versions that modify the stored JSON in a non back-compatible way. Because of this, if you update to a new version, continuing a game fails when trying to load.

**Comment by zampierilucas** [comment]
@ricott1 Yes, I got it when creating a new game. If I delete the `~/.config/rebels/world.json` file, it crashes again on the new game, with the same error message. Tested again with 1.0.4.

Also, I'm not sure why you closed this issue, it has definitely not been resolved.
