### ISSUE TITLE
v1.0.16 is released multiple times

### ISSUE THREAD

**Issue by orhun** [ricott1/rebels-in-the-sky#11]
Hello! I realized `v1.0.16` is pushed to the GitHub multiple times. This affects the Arch Linux package's reproducibility since the integrity checksums change every time. Would you please do minor releases instead of re-tagging the same release? 🙏🏼 Thanks!

**Comment by ricott1** [comment]
Hi @orhun , sure, sorry about that. I'm testing github actions and I can't get to auto upload compiled binaries to the release assets. If you have experience with that, could you maybe help me?

**Comment by orhun** [comment]
No worries, sure thing, I think first you need to adjust the workflow permissions to allow writing to the repository:

> Resource not accessible by integration

Settings -> Actions -> General -> Workflow Permissions -> Read and Write

**Comment by ricott1** [comment]
Done

**Comment by orhun** [comment]
Did it work? 🙂

**Comment by ricott1** [comment]
I solved it with a script :) I only use the action for the ubuntu release

**Comment by orhun** [comment]
alright 🤝
