### ISSUE TITLE
Use ratatui stable/alpha version

### ISSUE THREAD

**Issue by orhun** [ricott1/rebels-in-the-sky#12]
Hey, I saw that you are using a `git` dependency for Ratatui. I was wondering what is the reason for that & can you maybe use alpha versions instead? Asking for the reproduciblity of the Arch package :)

We are planning to release a new version soon btw

**Comment by ricott1** [comment]
Hi, makes sense.

I'm using the last from Ratatui cause I needed access to the `writer_mut` feature and I needed to release already cause I'm presenting the game somewhere. 

The problem however is that I'd still need to point to a fork of tui-textarea... Maybe it would just be better to skip this release for the moment and wait for ratatui 0.28.2 and the bump in tui-textarea?

**Comment by orhun** [comment]
I see. I agree that it might be safer to just wait. I'm aiming to push a release early next week so it should be fine :)

**Comment by ricott1** [comment]
New release with stable dependencies :)
