### ISSUE TITLE
Description typo/Video not working

### ISSUE THREAD

**Issue by augaug** [ricott1/rebels-in-the-sky#18]
Should say "means of survival" in description. Also, my YouTube window is blank/greyed out/unable to play for some reason.

![image](https://github.com/user-attachments/assets/ec0392ae-6800-43c6-8b73-09987d587924)

**Comment by ricott1** [comment]
Yeah, I'll have to convert it to a gif at some point. For the moment, this should work: https://streamable.com/huxiwr

**Comment by ricott1** [comment]
I added a link to the youtube video to the README
