### ISSUE TITLE
Keep demo updated

### ISSUE THREAD

**Issue by ricott1** [ricott1/rebels-in-the-sky#4]
The demo in the readme should be updated somewhat regularly to reflect updates to the game

**Comment by orhun** [comment]
You can prepare a [vhs tape](https://github.com/charmbracelet/vhs) for generating the GIF for each release and update it accordingly to the new features 🐻 

- Example: https://github.com/orhun/flawz/blob/main/assets/demo.tape
- Output: https://github.com/orhun/flawz/blob/main/assets/demo.gif

It even has a GitHub Action: <https://github.com/charmbracelet/vhs-action>

**Comment by ricott1** [comment]
For the moment I just update a new demo 'by hand'.
