### ISSUE TITLE
SSH won't authorize

### ISSUE THREAD

**Issue by MrPandir** [ricott1/rebels-in-the-sky#8]
You probably enabled password login.

<img width="877" src="https://github.com/ricott1/rebels-in-the-sky/assets/137798474/6bea983b-b6ce-4b93-a33a-69a64a13d706">

**Comment by ricott1** [comment]
Hey, yeah I did, but the password isn't checked at all. What happens if you try to enter any passowrd and return (empty password should be fine, for instance)

**Comment by ricott1** [comment]
Actually I had disabled the password auth, try now :)

**Comment by MrPandir** [comment]
@ricott1 yes, it worked. ❤️
